// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxngzitxvqawavyagwmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4bmd6aXR4dnFhd2F2eWFnd21vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTI4OTUsImV4cCI6MjA2MjQ2ODg5NX0.nolfX7vxuWWuM6-KVq5r6Dz9RV2gqBpqFiMulLgF0qE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);